# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Merten\PycharmProjects\Auswertungs_software\GUI\Hilfe/editor_hilfe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_help_editor(object):
    def setupUi(self, help_editor):
        help_editor.setObjectName("help_editor")
        help_editor.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(help_editor)
        self.centralwidget.setObjectName("centralwidget")
        help_editor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(help_editor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        help_editor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(help_editor)
        self.statusbar.setObjectName("statusbar")
        help_editor.setStatusBar(self.statusbar)

        self.retranslateUi(help_editor)
        QtCore.QMetaObject.connectSlotsByName(help_editor)

    def retranslateUi(self, help_editor):
        _translate = QtCore.QCoreApplication.translate
        help_editor.setWindowTitle(_translate("help_editor", "Hilfe - Labyrintheditor"))
