# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Merten\PycharmProjects\Auswertungs_software\GUI\Hilfe/main_hilfe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_help_main(object):
    def setupUi(self, help_main):
        help_main.setObjectName("help_main")
        help_main.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(help_main)
        self.centralwidget.setObjectName("centralwidget")
        help_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(help_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        help_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(help_main)
        self.statusbar.setObjectName("statusbar")
        help_main.setStatusBar(self.statusbar)

        self.retranslateUi(help_main)
        QtCore.QMetaObject.connectSlotsByName(help_main)

    def retranslateUi(self, help_main):
        _translate = QtCore.QCoreApplication.translate
        help_main.setWindowTitle(_translate("help_main", "Hilfe - Hauptprogramm"))
