# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Merten\PycharmProjects\Auswertungs_software\GUI/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WMainWindow(object):
    def setupUi(self, WMainWindow):
        WMainWindow.setObjectName("WMainWindow")
        WMainWindow.resize(964, 882)
        self.centralwidget = QtWidgets.QWidget(WMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Lcamera_preview = QtWidgets.QLabel(self.centralwidget)
        self.Lcamera_preview.setGeometry(QtCore.QRect(30, 20, 491, 261))
        self.Lcamera_preview.setObjectName("Lcamera_preview")
        self.Bretakeimage = QtWidgets.QPushButton(self.centralwidget)
        self.Bretakeimage.setGeometry(QtCore.QRect(20, 300, 121, 23))
        self.Bretakeimage.setObjectName("Bretakeimage")
        self.Bclassify = QtWidgets.QPushButton(self.centralwidget)
        self.Bclassify.setEnabled(False)
        self.Bclassify.setGeometry(QtCore.QRect(160, 300, 91, 23))
        self.Bclassify.setObjectName("Bclassify")
        self.Lpreview_classification = QtWidgets.QLabel(self.centralwidget)
        self.Lpreview_classification.setGeometry(QtCore.QRect(20, 330, 501, 471))
        self.Lpreview_classification.setObjectName("Lpreview_classification")
        self.Bsimulate = QtWidgets.QPushButton(self.centralwidget)
        self.Bsimulate.setEnabled(False)
        self.Bsimulate.setGeometry(QtCore.QRect(10, 810, 75, 23))
        self.Bsimulate.setObjectName("Bsimulate")
        self.Lsimulation = QtWidgets.QLabel(self.centralwidget)
        self.Lsimulation.setGeometry(QtCore.QRect(540, 10, 421, 791))
        self.Lsimulation.setObjectName("Lsimulation")
        self.Bcancelvideo = QtWidgets.QPushButton(self.centralwidget)
        self.Bcancelvideo.setEnabled(False)
        self.Bcancelvideo.setGeometry(QtCore.QRect(434, 300, 91, 23))
        self.Bcancelvideo.setObjectName("Bcancelvideo")
        self.BstartVideo = QtWidgets.QPushButton(self.centralwidget)
        self.BstartVideo.setEnabled(False)
        self.BstartVideo.setGeometry(QtCore.QRect(350, 300, 75, 23))
        self.BstartVideo.setObjectName("BstartVideo")
        self.BshowSimulation = QtWidgets.QPushButton(self.centralwidget)
        self.BshowSimulation.setEnabled(False)
        self.BshowSimulation.setGeometry(QtCore.QRect(100, 810, 111, 23))
        self.BshowSimulation.setObjectName("BshowSimulation")
        WMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 21))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        WMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WMainWindow)
        self.statusbar.setObjectName("statusbar")
        WMainWindow.setStatusBar(self.statusbar)
        self.actionLabyrinth_Editor = QtWidgets.QAction(WMainWindow)
        self.actionLabyrinth_Editor.setObjectName("actionLabyrinth_Editor")
        self.actionEinstellungen = QtWidgets.QAction(WMainWindow)
        self.actionEinstellungen.setObjectName("actionEinstellungen")
        self.actionSettings = QtWidgets.QAction(WMainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionEinstellungen_3 = QtWidgets.QAction(WMainWindow)
        self.actionEinstellungen_3.setObjectName("actionEinstellungen_3")
        self.actionHilfe = QtWidgets.QAction(WMainWindow)
        self.actionHilfe.setObjectName("actionHilfe")
        self.menuTools.addAction(self.actionLabyrinth_Editor)
        self.menuTools.addAction(self.actionSettings)
        self.menuTools.addSeparator()
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(WMainWindow)
        QtCore.QMetaObject.connectSlotsByName(WMainWindow)

    def retranslateUi(self, WMainWindow):
        _translate = QtCore.QCoreApplication.translate
        WMainWindow.setWindowTitle(_translate("WMainWindow", "BeLL-Projekt"))
        self.Lcamera_preview.setText(_translate("WMainWindow", "Kamera-Vorschau"))
        self.Bretakeimage.setText(_translate("WMainWindow", "Bild erneut aufnehmen"))
        self.Bclassify.setText(_translate("WMainWindow", "Klassifizieren"))
        self.Lpreview_classification.setText(_translate("WMainWindow", "Klassifikations-Vorschau"))
        self.Bsimulate.setText(_translate("WMainWindow", "Simulation"))
        self.Lsimulation.setText(_translate("WMainWindow", "Labyrinth-Vorschau/Simulation"))
        self.Bcancelvideo.setText(_translate("WMainWindow", "Video abbrechen"))
        self.BstartVideo.setText(_translate("WMainWindow", "Video starten"))
        self.BshowSimulation.setText(_translate("WMainWindow", "Simulation anzeigen"))
        self.menuTools.setTitle(_translate("WMainWindow", "Tools"))
        self.actionLabyrinth_Editor.setText(_translate("WMainWindow", "Labyrinth-Editor"))
        self.actionEinstellungen.setText(_translate("WMainWindow", "Einstellungen"))
        self.actionSettings.setText(_translate("WMainWindow", "Einstellungen (nicht implementiert)"))
        self.actionEinstellungen_3.setText(_translate("WMainWindow", "Einstellungen"))
        self.actionHilfe.setText(_translate("WMainWindow", "Hilfe"))
