# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Merten\PycharmProjects\Auswertungs_software\GUI/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WSettingsWindow(object):
    def setupUi(self, WSettingsWindow):
        WSettingsWindow.setObjectName("WSettingsWindow")
        WSettingsWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(WSettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Bcancel = QtWidgets.QPushButton(self.centralwidget)
        self.Bcancel.setGeometry(QtCore.QRect(90, 0, 75, 23))
        self.Bcancel.setObjectName("Bcancel")
        self.Bapply = QtWidgets.QPushButton(self.centralwidget)
        self.Bapply.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.Bapply.setObjectName("Bapply")
        self.CUseVideo = QtWidgets.QCheckBox(self.centralwidget)
        self.CUseVideo.setEnabled(False)
        self.CUseVideo.setGeometry(QtCore.QRect(10, 50, 81, 17))
        self.CUseVideo.setObjectName("CUseVideo")
        self.CUseInteraction = QtWidgets.QCheckBox(self.centralwidget)
        self.CUseInteraction.setEnabled(False)
        self.CUseInteraction.setGeometry(QtCore.QRect(10, 70, 91, 17))
        self.CUseInteraction.setObjectName("CUseInteraction")
        self.CSimulateLive = QtWidgets.QCheckBox(self.centralwidget)
        self.CSimulateLive.setEnabled(False)
        self.CSimulateLive.setGeometry(QtCore.QRect(10, 90, 91, 17))
        self.CSimulateLive.setObjectName("CSimulateLive")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 271, 16))
        self.label.setObjectName("label")
        WSettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WSettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        WSettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WSettingsWindow)
        self.statusbar.setObjectName("statusbar")
        WSettingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(WSettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(WSettingsWindow)

    def retranslateUi(self, WSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        WSettingsWindow.setWindowTitle(_translate("WSettingsWindow", "Einstellungen"))
        self.Bcancel.setText(_translate("WSettingsWindow", "Abbrechen"))
        self.Bapply.setText(_translate("WSettingsWindow", "Anwenden"))
        self.CUseVideo.setText(_translate("WSettingsWindow", "Video nutzen"))
        self.CUseInteraction.setText(_translate("WSettingsWindow", "Interaktionen"))
        self.CSimulateLive.setText(_translate("WSettingsWindow", "Live simulieren"))
        self.label.setText(_translate("WSettingsWindow", "Diese Einstellungen sind aktuell noch nicht implementiert"))
